# This is a basic workflow to help you get started with Actions

name: deploy production

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - master

  # Allows you to run this workflow manually from the Actions tab
  #   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: build, dploy ro s3 bucket
    runs-on: [ubuntu-latest]
    
    strategy:
      matrix:
        node-version: [12.2.0-alpine]
    steps:
      - name: use node.js ${{matrix.node-version}}
      - uses: actions/checkout@v2
        with:
          node-version: ${{matrix.node-version}}
      
      - name: npm install
        run: npm install
        
      - name: build
        run: npm run build
         
      - name: transfer to s3 for serving static
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: wookimbb
          AWS_ACCESS_KEY_ID: ${{ secrets. AWS_IAM_MANAGER_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
          SOURCE_DIR: 'dist'
