name: deploy production

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    name: Build deploy to S3 bucket
    runs-on: [ubuntu-latest]
    
    strategy:
      matrix:
        node-version: [14.15.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules      # node modules 캐싱
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      
      - name: npm install
        run: npm install

      - name: build
        run: npm run build

      - name: make artifacts dir
        run: mkdir ./artifacts/
        
      - name: copy appspec file to build folder
        run: cp appspec.yml ./artifacts/

      - name: zip artifacts
        run: zip ./artifacts/build.zip ./build/*

      - name: check dir 
        run: ls

      - name: transfer to s3 for serving static
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{secrets.AWS_PRODUCTION_BUCKET_NAME}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
          # FILE: ./build.zip
          SOURCE_DIR: './artifacts'
          DEST_DIR: 'front/'
