name: deploy production

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    name: Build deploy to S3 bucket
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.15.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: npm install
        run: npm install
        
      - name: build
        run: npm run build
         
      - name: transfer to s3 for serving static
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: wookimbb
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
          SOURCE_DIR: 'dist'
